### ISSUE TITLE
modules description

### ISSUE THREAD

**Issue by nitawa** [SalomePlatform/.github#2]
add a new wiki page which describes shortly (max 2 lines) each repository  aka module.

**Comment by mohd-afeef-badri** [comment]
Great idea, indeed we should do this task and also tag each module in terms of its functionalities.

**Comment by wrxhardworking** [comment]
where is SALOMEDeveloper.bat？

**Comment by mohd-afeef-badri** [comment]
@nitawa, I've written one-liner descriptions for nearly all missing modules and tagged them accordingly. Feel free to close this issue if you agree.

**Comment by nitawa** [comment]
thanks.
