### ISSUE TITLE
Prepare SALOME source code failed

### ISSUE THREAD

**Issue by dx123321** [SalomePlatform/.github#4]
Building SALOME on Linux：
   Execute command：SAT/sat -o "APPLICATION.properties.git_server='github'"  prepare SALOME-9.11.0-native
![image](https://github.com/user-attachments/assets/9ae7d84e-c9fe-4451-824a-491a079a4293)

How to modify GIT address，or How to register an account and password for this website?
website address:https://codev-tuleap.cea.fr/

**Comment by nitawa** [comment]
thanks for reporting about this. Indeed we did not migrate SALOME-9.11. we just pushed the fix. In the meanwhile, until it gets mirrored to GitHub, here is what you can do:

 you need to edit sat_salome/applications/SALOME-9.11.0-native.pyconf and replace ` repo_dev : "yes"` with ` git_server : 'tuleap'`

```
    properties :
    {
        mesa_launcher_in_package : "yes"
        git_server : 'tuleap'
        pip : 'yes'
        pip_install_dir : 'python'
        single_install_dir : "no"
    }

```

**Comment by nitawa** [comment]
It should be ok now.  Thanks for reporting about this issue.

**Comment by dx123321** [comment]
edit sat_salome/applications/SALOME-9.11.0-native.pyconf and replace with  repo_dev : "yes" git_server : 'tuleap'：
`    properties :
    {
        mesa_launcher_in_package : "yes"
        git_server : 'tuleap'
        #repo_dev : "yes"
        pip : 'yes'
        pip_install_dir : 'python'
        single_install_dir : "no"
    }
`

Building SALOME on Linux：
Execute command：SAT/sat -o "APPLICATION.properties.git_server='github'" prepare SALOME-9.11.0-native：
`CONFIGURATION:              git:https://git.salome-platform.org/gitpub/tools/configuration.git               tag:V9_11_0 .... OK
SALOME:                     git:https://codev-tuleap.cea.fr/plugins/git/salome/SALOME.git                    tag:V9_11_0 .... Username for 'https://codev-tuleap.cea.fr':
`

You may need to push through the remaining module code：
`        # SALOME MODULES :
        'CONFIGURATION'
        'SALOME'
        'SHAPER'
        'SHAPERSTUDY'
        'RESTRICTED'
        'LIBBATCH' : 'V2_4_6'
        'KERNEL'
        'MEDCOUPLING' : {tag:'V9_11_0', base: 'no', section: 'default_MPI', hpc: 'yes'}
        'GUI'
        'GEOM'
        'SMESH'
        'NETGENPLUGIN'
        'BLSURFPLUGIN'
        'GHS3DPLUGIN'
        'HYBRIDPLUGIN'
        'HexoticPLUGIN'
        'GMSHPLUGIN'
        'HEXABLOCK'
        'HEXABLOCKPLUGIN'
        'HOMARD'
        'FIELDS'
        'PARAVIS': {tag:'V9_11_0', base: 'no', section: 'default_MPI', hpc: 'yes'}
        'JOBMANAGER'
        'YACS'
        'YACSGEN'
        'DOCUMENTATION'
        'SAMPLES'
        'COMPONENT'
        'PYCALCULATOR'
        'CALCULATOR'
        'HELLO'
        'PYHELLO'
        'EFICAS'
        'EFICAS_TOOLS'
        'PY2CPP'
        'ADAO'
        'ADAO_INTERFACE'
        'PARAVISADDONS'
        'OPENTURNS_SALOME'
        'YDEFX'
        'pmml'
        'SOLVERLAB'
        'SOLVERLABGUI'
        'TopIIVolMesh'
        #'TESTBASE'
        'CEATESTBASE' : 'SalomeV9'
`

**Comment by dx123321** [comment]
> 感谢您对此进行报告。事实上，我们没有迁移 SALOME-9.11。我们刚刚推动了修复。同时，在它被镜像到 GitHub 之前，您可以执行以下操作：
> 
> 您需要编辑 sat_salome/applications/SALOME-9.11.0-native.pyconf 并替换为` repo_dev : "yes"`` git_server : 'tuleap'`
> 
> ```
>     properties :
>     {
>         mesa_launcher_in_package : "yes"
>         git_server : 'tuleap'
>         pip : 'yes'
>         pip_install_dir : 'python'
>         single_install_dir : "no"
>     }
> ```

编辑 sat_salome/applications/SALOME-9.11.0-native.pyconf 并替换为 repo_dev ： “yes” git_server ： 'tuleap'：
   properties : { mesa_launcher_in_package : "yes" git_server : 'tuleap' #repo_dev : "yes" pip : 'yes' pip_install_dir : 'python' single_install_dir : "no" }

在 Linux 上构建 SALOME：
执行命令：SAT/sat -o “APPLICATION.properties.git_server='github'” 准备 SALOME-9.11.0-native：
CONFIGURATION:              git:https://git.salome-platform.org/gitpub/tools/configuration.git               tag:V9_11_0 .... OK SALOME:                     git:https://codev-tuleap.cea.fr/plugins/git/salome/SALOME.git                    tag:V9_11_0 .... Username for 'https://codev-tuleap.cea.fr': 

您可能需要推送剩余的模块代码：
       # SALOME MODULES : 'CONFIGURATION' 'SALOME' 'SHAPER' 'SHAPERSTUDY' 'RESTRICTED' 'LIBBATCH' : 'V2_4_6' 'KERNEL' 'MEDCOUPLING' : {tag:'V9_11_0', base: 'no', section: 'default_MPI', hpc: 'yes'} 'GUI' 'GEOM' 'SMESH' 'NETGENPLUGIN' 'BLSURFPLUGIN' 'GHS3DPLUGIN' 'HYBRIDPLUGIN' 'HexoticPLUGIN' 'GMSHPLUGIN' 'HEXABLOCK' 'HEXABLOCKPLUGIN' 'HOMARD' 'FIELDS' 'PARAVIS': {tag:'V9_11_0', base: 'no', section: 'default_MPI', hpc: 'yes'} 'JOBMANAGER' 'YACS' 'YACSGEN' 'DOCUMENTATION' 'SAMPLES' 'COMPONENT' 'PYCALCULATOR' 'CALCULATOR' 'HELLO' 'PYHELLO' 'EFICAS' 'EFICAS_TOOLS' 'PY2CPP' 'ADAO' 'ADAO_INTERFACE' 'PARAVISADDONS' 'OPENTURNS_SALOME' 'YDEFX' 'pmml' 'SOLVERLAB' 'SOLVERLABGUI' 'TopIIVolMesh' #'TESTBASE' 'CEATESTBASE' : 'SalomeV9'

**Comment by nitawa** [comment]
This is strange. Note that you need to use SAT master branch. 
Can you then simply edit the pyconf ``SALOME-9.11.0-native.pyconf`` file and set git_server to github?

Then rerun `` SAT/sat prepare  SALOME-9.11.0-native``

**Comment by dx123321** [comment]
> This is strange. Note that you need to use SAT master branch. Can you then simply edit the pyconf `SALOME-9.11.0-native.pyconf` file and set git_server to github?
> 
> Then rerun ` SAT/sat prepare SALOME-9.11.0-native`

This method is not feasible and has been tried，pull the source code from this address：git:https://codev-tuleap.cea.fr/plugins/git/salome/SALOME.git，No account password

**Comment by dx123321** [comment]
![image](https://github.com/user-attachments/assets/ddc6d288-1c55-4773-a08a-5aeae4d6ff10)


> This is strange. Note that you need to use SAT master branch. Can you then simply edit the pyconf `SALOME-9.11.0-native.pyconf` file and set git_server to github?
> 
> Then rerun ` SAT/sat prepare SALOME-9.11.0-native`

![image](https://github.com/user-attachments/assets/b2242107-6463-4c00-8ba6-003595474e9d)


> > This is strange. Note that you need to use SAT master branch. Can you then simply edit the pyconf `SALOME-9.11.0-native.pyconf` file and set git_server to github?
> > Then rerun ` SAT/sat prepare SALOME-9.11.0-native`
> 
> This method is not feasible and has been tried，pull the source code from this address：git:[https://codev-tuleap.cea.fr/plugins/git/salome/SALOME.git，No](https://codev-tuleap.cea.fr/plugins/git/salome/SALOME.git%EF%BC%8CNo) account password

![image](https://github.com/user-attachments/assets/3f6516bf-dad4-421a-b95f-a16b9fbc7807)

**Comment by dx123321** [comment]
> thanks for reporting about this. Indeed we did not migrate SALOME-9.11. we just pushed the fix. In the meanwhile, until it gets mirrored to GitHub, here is what you can do:
> 
> you need to edit sat_salome/applications/SALOME-9.11.0-native.pyconf and replace ` repo_dev : "yes"` with ` git_server : 'tuleap'`
> 
> ```
>     properties :
>     {
>         mesa_launcher_in_package : "yes"
>         git_server : 'tuleap'
>         pip : 'yes'
>         pip_install_dir : 'python'
>         single_install_dir : "no"
>     }
> ```

Previously, the configuration model could not be downloaded. After performing this operation, the CONFIGURATION model can be downloaded, but the remaining modules cannot be downloaded. Is it because Tuleap doesn't have remaining module source code?
![image](https://github.com/user-attachments/assets/5603e972-122e-4c5c-99d6-28388adec8b6)
