### ISSUE TITLE
Prepare SALOME source code failed

### ISSUE THREAD

**Issue by dx123321** [SalomePlatform/.github#5]
Building SALOME on Linux：
Execute command：SAT/sat -o "APPLICATION.properties.git_server='github'" prepare SALOME-9.11.0-native：
![image](https://github.com/user-attachments/assets/424c5052-5a85-46e6-89b0-c72dadce72bf)

Edit sat_salome/applications/SALOME-9.11.0-native.pyconf and replace  repo_dev : "yes" with  git_server : 'tuleap'：
`    properties :
    {
        mesa_launcher_in_package : "yes"
        git_server : 'tuleap'
        pip : 'yes'
        pip_install_dir : 'python'
        single_install_dir : "no"
    }
`
This method is not feasible and has been tried，pull the source code from this address：git:[https://codev-tuleap.cea.fr/plugins/git/salome/SALOME.git，No account password:
![image](https://github.com/user-attachments/assets/a0ada865-1740-4413-a904-7e1b36cb6833)

Previously, the CONFIGURATION model could not be downloaded. After performing this operation, the CONFIGURATION model can be downloaded, but the remaining modules cannot be downloaded. Is it because Tuleap doesn't have remaining module source code?
![image](https://github.com/user-attachments/assets/f166df71-db3e-4fe6-abbc-6a9bce16c500)

**Comment by dx123321** [comment]
@nitawa @asonolet @mohd-afeef-badri 
Excuse me, could you please help me take a look at this issue？

**Comment by nitawa** [comment]
Hi,
apologize for the late reply. I just checked by following the wiki page and  did not manage to reproduce your issue.
Can you follow the wiki, namely the following command lines and check if you did not miss one step?
In addition, what Linux platform are you running (check `cat /etc/os-release` output)

```shell
export SALOME_WORKSPACE=$PWD
git clone https://github.com/SalomePlatform/sat.git SAT
git clone https://github.com/SalomePlatform/sat_salome.git SAT_SALOME
SAT/sat init --add_project $SALOME_WORKSPACE/SAT_SALOME/salome.pyconf
SAT/sat config SALOME-master-native --check_system
SAT/sat -o "APPLICATION.properties.git_server='github'" prepare SALOME-9.11.0-native

```
Regards.

![image](https://github.com/user-attachments/assets/d094cc0f-3d6d-4319-9a18-6af3faa2845d)

![image](https://github.com/user-attachments/assets/0a4ecd3f-02ea-43f3-8ddd-184b58c9b1d2)

**Comment by dx123321** [comment]
> Hi, apologize for the late reply. I just checked by following the wiki page and did not manage to reproduce your issue. Can you follow the wiki namely the following command lines and check if you did not miss one step? In addition, what Linux platform are you running (check `cat /etc/os-release` output)
> 
> ```shell
> export SALOME_WORKSPACE=$PWD
> git clone https://github.com/SalomePlatform/sat.git SAT
> git clone https://github.com/SalomePlatform/sat_salome.git SAT_SALOME
> SAT/sat init --add_project $SALOME_WORKSPACE/SAT_SALOME/salome.pyconf
> SAT/sat config SALOME-master-native --check_system
> SAT/sat -o "APPLICATION.properties.git_server='github'" prepare SALOME-9.11.0-native
> ```
> 
> Regards.
> 
> ![image](https://private-user-images.githubusercontent.com/3521545/359020267-d094cc0f-3d6d-4319-9a18-6af3faa2845d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTQ1MzgsIm5iZiI6MTcyNDA1NDIzOCwicGF0aCI6Ii8zNTIxNTQ1LzM1OTAyMDI2Ny1kMDk0Y2MwZi0zZDZkLTQzMTktOWExOC02YWYzZmFhMjg0NWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMDc1NzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGIxZTU1NjRhYWQ4ZmY3NTdiZTBmNzAzZWRlN2JjNzVkNGZiZjE2MDU4MWMzYjZlMzlmZTdiMTkzNWYzNWNhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZcSw_uIVyesEqRuO5KVDOpLtqPJP8lJQH5D--3W0ivo)
> 
> ![image](https://private-user-images.githubusercontent.com/3521545/359021376-0a4ecd3f-02ea-43f3-8ddd-184b58c9b1d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTQ1MzgsIm5iZiI6MTcyNDA1NDIzOCwicGF0aCI6Ii8zNTIxNTQ1LzM1OTAyMTM3Ni0wYTRlY2QzZi0wMmVhLTQzZjMtOGRkZC0xODRiNThjOWIxZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMDc1NzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWExY2FiNjllOWE2YWViOWJiYzY1NmFiOTFiMTAwZTI1ZDY3OGQzM2Q5Nzk5YjMwZTI0YTYyNTZmOTUzZTZjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.avQQgeKr-ltGNuzNBOF8B2TMsHqoBr3LS_3-VlnrFOs)

According to the method you provided, run it again and report the following error：

> WARNING: Some run time system dependencies are missing!
Please install them with dpkg-query before running salome
missing run time dependencies : libquadmath0

WARNING: RESTRICTED is a closed-source software and is not available on github
WARNING: CEATESTBASE is a closed-source software and is not available on github
Clean the source directories ...OK
Getting sources of the application SALOME-9.11.0-native
  workdir = /root/dx/SALOME-9.11.0-native-UB22.04

alabaster:                  Native : Checking system packages are installed
 - python3-alabaster : OK
Babel:                      Native : Checking system packages are installed
 - python3-babel : OK
boost:                      Native : Checking system packages are installed
 - libboost-all-dev : OK
CAS:                        GIT:http://git.dev.opencascade.org/repos/occt.git                                tag:V7_5_3p5 ... OK
catalyst:
   The archive is not found on local file system, we try ftp
ERROR: while connecting to ftp server ftp.cea.fr


***** salomeTools ERROR: sat source *****
<bound method SatException.message of SatException("Archive not found in ARCHIVEPATH, nor on ARCHIVEFTP: 'catalyst-2.0-431a8a1.tar.gz'")>
Patching sources of the application SALOME-9.11.0-native
  workdir = /root/dx/SALOME-9.11.0-native-UB22.04

C3PO:                       No sources found for the C3PO product
FMILibrary:                 No sources found for the FMILibrary product
hdf5:                       No sources found for the hdf5 product
medfile:                    No sources found for the medfile product
netgen:                     No sources found for the netgen product
netcdf:                     No sources found for the netcdf product
omniORB:                    No sources found for the omniORB product
omniORBpy:                  No sources found for the omniORBpy product
opencv:                     No sources found for the opencv product
openturns:                  No sources found for the openturns product
packagespy:                 No sources found for the packagespy product
ParaView:                   No sources found for the ParaView product
petsc:                      No sources found for the petsc product
PyFMI:                      No sources found for the PyFMI product
root:                       No sources found for the root product
TTK:                        No sources found for the TTK product
URANIE:                     No sources found for the URANIE product

Patching sources of the application: KO (125 / 142)


The Linux platform is：

> PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by nitawa** [comment]
There must be some glitch in your internet connexion. `catalyst-2.0-431a8a1.tar.gz` is available on the anonymous ftp site.
You can check it with:
```shell
curl ftp://ftp.cea.fr/pub/salome/prerequisites/catalyst-2.0-431a8a1.tar.gz -o catalyst-2.0-431a8a1.tar.gz
```

**Comment by dx123321** [comment]
> There must be some glitch in your internet connexion. `catalyst-2.0-431a8a1.tar.gz` is available on the anonymous ftp site. You can check it with:
> 
> ```shell
> curl ftp://ftp.cea.fr/pub/salome/prerequisites/catalyst-2.0-431a8a1.tar.gz -o catalyst-2.0-431a8a1.tar.gz
> ```

There are indeed issues with the internet. Is there a way to extract all packages and modules separately, compile and install SALOME? If running according to Wiki scripts, my network environment is limited

**Comment by nitawa** [comment]
here is what you can do:

- download SALOME 9.11 archive for your UB22.04 from official SALOME site (expect few GB :( .
- move all files  contained in SALOME-9.11.0-native-UB22.04-SRC/ARCHIVES to /`root/dx/ARCHIVES` 
-  edit file SAT_SALOME/salome.pyconf and set `ARCHIVEPATH : "/root/dx/ARCHIVES:/home/salome-public/prerequis/archives:/nfs/home/salome-public/prerequis/archives:/mnt/prerequis/archives"`
- and repeat steps  described [here](https://github.com/SalomePlatform/.github/issues/5#issuecomment-2295888928)

HTH

**Comment by nitawa** [comment]
let's close this issue. You can comment it further or open a new one if required. Regards.
